export const types = {
  SET_USER: "SET_USER",
  ADD_ITEM_WISHLIST: "ADD_ITEM_WISHLIST",
  REMOVE_ITEM_WISHLIST: "REMOVE_ITEM_WISHLIST",
  ADD_ITEM_CART: "ADD_ITEM_CART",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
};
