export const types = {
  SET_USER: "SET_USER",
  REMOVE_USER: "REMOVE_USER",
  ADD_ITEM_WISHLIST: "ADD_ITEM_WISHLIST",
  REMOVE_ITEM_WISHLIST: "REMOVE_ITEM_WISHLIST",
  ADD_ITEM_CART: "ADD_ITEM_CART",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
  FINISH_PAYMENT: "FINISH_PAYMENT",
  SET_CART_LOADING: "SET_CART_LOADING",
  SET_PAYMENT_STATUS: "SET_PAYMENT_STATUS"
};
